language: node_js
node_js:
  - "node"
  - "8"
  - "7"
install:
  - yarn install
  - yarn install -g codecov
cache:
  directories:
    - "node_modules"
script:
  - yarn test -- --coverage
after_success:
  - codecov
  - yarn run build
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    branch: "master"
    node: "node"
    tags: true
git:
  depth: 9999999
