export const FETCH_GEO_IP_ADDRESS_REQUEST =
  'geoIp/FETCH_GEO_IP_ADDRESS_REQUEST';
export const FETCH_GEO_IP_ADDRESS_SUCCESS =
  'geoIp/FETCH_GEO_IP_ADDRESS_SUCCESS';
export const FETCH_GEO_IP_ADDRESS_FAILURE =
  'geoIp/FETCH_GEO_IP_ADDRESS_FAILURE';
