export const FETCH_WEATHER_FORECAST_REQUEST = 'weather/FETCH_WEATHER_FORECAST_REQUEST';
export const FETCH_WEATHER_FORECAST_SUCCESS = 'weather/FETCH_WEATHER_FORECAST_SUCCESS';
export const FETCH_WEATHER_FORECAST_FAILURE = 'weather/FETCH_WEATHER_FORECAST_FAILURE';
